import sys
import pytest
sys.path.append(".")
from dna import DNA
from pathlib import Path

# create objects
TEST_KMER_LEN = 20
GENOME_REF_PATH = "/Users/latifa/GitHub/Phage-EnrichSeq/jaccard_module/"
GENOME = ("GTCTCCGAGCGATCTATCCACGACCAATTTGACATGGGTGCGCCGTTTGT"
        "AAAGGCCGTGGACAAAGCAGAACCCCCGGCACCGAGGGGGGCCGGGGGCC"
        "TGTTGGCGTGACGCCGTTGCTGCGCTCTTGGGGGTAGACGCGTCTCTCAG")
test_dna = DNA("Blessica", GENOME_REF_PATH + "Blessica.fasta", TEST_KMER_LEN)
compare_dna = DNA("Ryadel", GENOME_REF_PATH + "Ryadel.fasta", TEST_KMER_LEN)

def test_init():
    ''' Test constructor '''
    dna1 = DNA("D29", GENOME_REF_PATH + "D29.fasta", TEST_KMER_LEN)
    assert dna1.name == "D29"
    assert dna1.fasta_file == Path("/Users/latifa/GitHub/Phage-EnrichSeq/jaccard_module/D29.fasta")
    assert dna1.genome == ("TGCGGCCGAGCCATCCTGTACGGGTTTCCAAGCCGATCAGAAGCACGGGC"
                            "CGACGCTAGAGCGCCTCGCCCAGGCGCTGTGAGCCACCAGGAGCCACGAA"
                            "CTCGCGACCCACGGGGAGTTATACCCCCGGAATCGGCTACGGGCCATACA")
    assert dna1.kmers == ['TGCGGCCGAGCCATCCTGTA', 'GCGGCCGAGCCATCCTGTAC', 'CGGCCGAGCCATCCTGTACG', 'GGCCGAGCCATCCTGTACGG', 'GCCGAGCCATCCTGTACGGG', 'CCGAGCCATCCTGTACGGGT', 'CGAGCCATCCTGTACGGGTT', 'GAGCCATCCTGTACGGGTTT', 'AGCCATCCTGTACGGGTTTC', 'GCCATCCTGTACGGGTTTCC', 'CCATCCTGTACGGGTTTCCA', 'CATCCTGTACGGGTTTCCAA', 'ATCCTGTACGGGTTTCCAAG', 'TCCTGTACGGGTTTCCAAGC', 'CCTGTACGGGTTTCCAAGCC', 'CTGTACGGGTTTCCAAGCCG', 'TGTACGGGTTTCCAAGCCGA', 'GTACGGGTTTCCAAGCCGAT', 'TACGGGTTTCCAAGCCGATC', 'ACGGGTTTCCAAGCCGATCA', 'CGGGTTTCCAAGCCGATCAG', 'GGGTTTCCAAGCCGATCAGA', 'GGTTTCCAAGCCGATCAGAA', 'GTTTCCAAGCCGATCAGAAG', 'TTTCCAAGCCGATCAGAAGC', 'TTCCAAGCCGATCAGAAGCA', 'TCCAAGCCGATCAGAAGCAC', 'CCAAGCCGATCAGAAGCACG', 'CAAGCCGATCAGAAGCACGG', 'AAGCCGATCAGAAGCACGGG', 'AGCCGATCAGAAGCACGGGC', 'GCCGATCAGAAGCACGGGCC', 'CCGATCAGAAGCACGGGCCG', 'CGATCAGAAGCACGGGCCGA', 'GATCAGAAGCACGGGCCGAC', 'ATCAGAAGCACGGGCCGACG', 'TCAGAAGCACGGGCCGACGC', 'CAGAAGCACGGGCCGACGCT', 'AGAAGCACGGGCCGACGCTA', 'GAAGCACGGGCCGACGCTAG', 'AAGCACGGGCCGACGCTAGA', 'AGCACGGGCCGACGCTAGAG', 'GCACGGGCCGACGCTAGAGC', 'CACGGGCCGACGCTAGAGCG', 'ACGGGCCGACGCTAGAGCGC', 'CGGGCCGACGCTAGAGCGCC', 'GGGCCGACGCTAGAGCGCCT', 'GGCCGACGCTAGAGCGCCTC', 'GCCGACGCTAGAGCGCCTCG', 'CCGACGCTAGAGCGCCTCGC', 'CGACGCTAGAGCGCCTCGCC', 'GACGCTAGAGCGCCTCGCCC', 'ACGCTAGAGCGCCTCGCCCA', 'CGCTAGAGCGCCTCGCCCAG', 'GCTAGAGCGCCTCGCCCAGG', 'CTAGAGCGCCTCGCCCAGGC', 'TAGAGCGCCTCGCCCAGGCG', 'AGAGCGCCTCGCCCAGGCGC', 'GAGCGCCTCGCCCAGGCGCT', 'AGCGCCTCGCCCAGGCGCTG', 'GCGCCTCGCCCAGGCGCTGT', 'CGCCTCGCCCAGGCGCTGTG', 'GCCTCGCCCAGGCGCTGTGA', 'CCTCGCCCAGGCGCTGTGAG', 'CTCGCCCAGGCGCTGTGAGC', 'TCGCCCAGGCGCTGTGAGCC', 'CGCCCAGGCGCTGTGAGCCA', 'GCCCAGGCGCTGTGAGCCAC', 'CCCAGGCGCTGTGAGCCACC', 'CCAGGCGCTGTGAGCCACCA', 'CAGGCGCTGTGAGCCACCAG', 'AGGCGCTGTGAGCCACCAGG', 'GGCGCTGTGAGCCACCAGGA', 'GCGCTGTGAGCCACCAGGAG', 'CGCTGTGAGCCACCAGGAGC', 'GCTGTGAGCCACCAGGAGCC', 'CTGTGAGCCACCAGGAGCCA', 'TGTGAGCCACCAGGAGCCAC', 'GTGAGCCACCAGGAGCCACG', 'TGAGCCACCAGGAGCCACGA', 'GAGCCACCAGGAGCCACGAA', 'AGCCACCAGGAGCCACGAAC', 'GCCACCAGGAGCCACGAACT', 'CCACCAGGAGCCACGAACTC', 'CACCAGGAGCCACGAACTCG', 'ACCAGGAGCCACGAACTCGC', 'CCAGGAGCCACGAACTCGCG', 'CAGGAGCCACGAACTCGCGA', 'AGGAGCCACGAACTCGCGAC', 'GGAGCCACGAACTCGCGACC', 'GAGCCACGAACTCGCGACCC', 'AGCCACGAACTCGCGACCCA', 'GCCACGAACTCGCGACCCAC', 'CCACGAACTCGCGACCCACG', 'CACGAACTCGCGACCCACGG', 'ACGAACTCGCGACCCACGGG', 'CGAACTCGCGACCCACGGGG', 'GAACTCGCGACCCACGGGGA', 'AACTCGCGACCCACGGGGAG', 'ACTCGCGACCCACGGGGAGT', 'CTCGCGACCCACGGGGAGTT', 'TCGCGACCCACGGGGAGTTA', 'CGCGACCCACGGGGAGTTAT', 'GCGACCCACGGGGAGTTATA', 'CGACCCACGGGGAGTTATAC', 'GACCCACGGGGAGTTATACC', 'ACCCACGGGGAGTTATACCC', 'CCCACGGGGAGTTATACCCC', 'CCACGGGGAGTTATACCCCC', 'CACGGGGAGTTATACCCCCG', 'ACGGGGAGTTATACCCCCGG', 'CGGGGAGTTATACCCCCGGA', 'GGGGAGTTATACCCCCGGAA', 'GGGAGTTATACCCCCGGAAT', 'GGAGTTATACCCCCGGAATC', 'GAGTTATACCCCCGGAATCG', 'AGTTATACCCCCGGAATCGG', 'GTTATACCCCCGGAATCGGC', 'TTATACCCCCGGAATCGGCT', 'TATACCCCCGGAATCGGCTA', 'ATACCCCCGGAATCGGCTAC', 'TACCCCCGGAATCGGCTACG', 'ACCCCCGGAATCGGCTACGG', 'CCCCCGGAATCGGCTACGGG', 'CCCCGGAATCGGCTACGGGC', 'CCCGGAATCGGCTACGGGCC', 'CCGGAATCGGCTACGGGCCA', 'CGGAATCGGCTACGGGCCAT', 'GGAATCGGCTACGGGCCATA', 'GAATCGGCTACGGGCCATAC', 'AATCGGCTACGGGCCATACA']


def test_fasta_to_genome():
    ''' Test method that extracts a genome from a fasta file '''
    expected_genome = ("GTCTCCGAGCGATCTATCCACGACCAATTTGACATGGGTGCGCCGTTTGT"
                        "AAAGGCCGTGGACAAAGCAGAACCCCCGGCACCGAGGGGGGCCGGGGGCC"
                        "TGTTGGCGTGACGCCGTTGCTGCGCTCTTGGGGGTAGACGCGTCTCTCAG")
    actual_genome = test_dna.fasta_to_genome(test_dna.fasta_file)
    assert actual_genome == expected_genome

@pytest.mark.parametrize("kmer_len, expected",
                        [
                            (20, ['GTCTCCGAGCGATCTATCCA', 'TCTCCGAGCGATCTATCCAC', 'CTCCGAGCGATCTATCCACG', 'TCCGAGCGATCTATCCACGA', 'CCGAGCGATCTATCCACGAC', 'CGAGCGATCTATCCACGACC', 'GAGCGATCTATCCACGACCA', 'AGCGATCTATCCACGACCAA', 'GCGATCTATCCACGACCAAT', 'CGATCTATCCACGACCAATT', 'GATCTATCCACGACCAATTT', 'ATCTATCCACGACCAATTTG', 'TCTATCCACGACCAATTTGA', 'CTATCCACGACCAATTTGAC', 'TATCCACGACCAATTTGACA', 'ATCCACGACCAATTTGACAT', 'TCCACGACCAATTTGACATG', 'CCACGACCAATTTGACATGG', 'CACGACCAATTTGACATGGG', 'ACGACCAATTTGACATGGGT', 'CGACCAATTTGACATGGGTG', 'GACCAATTTGACATGGGTGC', 'ACCAATTTGACATGGGTGCG', 'CCAATTTGACATGGGTGCGC', 'CAATTTGACATGGGTGCGCC', 'AATTTGACATGGGTGCGCCG', 'ATTTGACATGGGTGCGCCGT', 'TTTGACATGGGTGCGCCGTT', 'TTGACATGGGTGCGCCGTTT', 'TGACATGGGTGCGCCGTTTG', 'GACATGGGTGCGCCGTTTGT', 'ACATGGGTGCGCCGTTTGTA', 'CATGGGTGCGCCGTTTGTAA', 'ATGGGTGCGCCGTTTGTAAA', 'TGGGTGCGCCGTTTGTAAAG', 'GGGTGCGCCGTTTGTAAAGG', 'GGTGCGCCGTTTGTAAAGGC', 'GTGCGCCGTTTGTAAAGGCC', 'TGCGCCGTTTGTAAAGGCCG', 'GCGCCGTTTGTAAAGGCCGT', 'CGCCGTTTGTAAAGGCCGTG', 'GCCGTTTGTAAAGGCCGTGG', 'CCGTTTGTAAAGGCCGTGGA', 'CGTTTGTAAAGGCCGTGGAC', 'GTTTGTAAAGGCCGTGGACA', 'TTTGTAAAGGCCGTGGACAA', 'TTGTAAAGGCCGTGGACAAA', 'TGTAAAGGCCGTGGACAAAG', 'GTAAAGGCCGTGGACAAAGC', 'TAAAGGCCGTGGACAAAGCA', 'AAAGGCCGTGGACAAAGCAG', 'AAGGCCGTGGACAAAGCAGA', 'AGGCCGTGGACAAAGCAGAA', 'GGCCGTGGACAAAGCAGAAC', 'GCCGTGGACAAAGCAGAACC', 'CCGTGGACAAAGCAGAACCC', 'CGTGGACAAAGCAGAACCCC', 'GTGGACAAAGCAGAACCCCC', 'TGGACAAAGCAGAACCCCCG', 'GGACAAAGCAGAACCCCCGG', 'GACAAAGCAGAACCCCCGGC', 'ACAAAGCAGAACCCCCGGCA', 'CAAAGCAGAACCCCCGGCAC', 'AAAGCAGAACCCCCGGCACC', 'AAGCAGAACCCCCGGCACCG', 'AGCAGAACCCCCGGCACCGA', 'GCAGAACCCCCGGCACCGAG', 'CAGAACCCCCGGCACCGAGG', 'AGAACCCCCGGCACCGAGGG', 'GAACCCCCGGCACCGAGGGG', 'AACCCCCGGCACCGAGGGGG', 'ACCCCCGGCACCGAGGGGGG', 'CCCCCGGCACCGAGGGGGGC', 'CCCCGGCACCGAGGGGGGCC', 'CCCGGCACCGAGGGGGGCCG', 'CCGGCACCGAGGGGGGCCGG', 'CGGCACCGAGGGGGGCCGGG', 'GGCACCGAGGGGGGCCGGGG', 'GCACCGAGGGGGGCCGGGGG', 'CACCGAGGGGGGCCGGGGGC', 'ACCGAGGGGGGCCGGGGGCC', 'CCGAGGGGGGCCGGGGGCCT', 'CGAGGGGGGCCGGGGGCCTG', 'GAGGGGGGCCGGGGGCCTGT', 'AGGGGGGCCGGGGGCCTGTT', 'GGGGGGCCGGGGGCCTGTTG', 'GGGGGCCGGGGGCCTGTTGG', 'GGGGCCGGGGGCCTGTTGGC', 'GGGCCGGGGGCCTGTTGGCG', 'GGCCGGGGGCCTGTTGGCGT', 'GCCGGGGGCCTGTTGGCGTG', 'CCGGGGGCCTGTTGGCGTGA', 'CGGGGGCCTGTTGGCGTGAC', 'GGGGGCCTGTTGGCGTGACG', 'GGGGCCTGTTGGCGTGACGC', 'GGGCCTGTTGGCGTGACGCC', 'GGCCTGTTGGCGTGACGCCG', 'GCCTGTTGGCGTGACGCCGT', 'CCTGTTGGCGTGACGCCGTT', 'CTGTTGGCGTGACGCCGTTG', 'TGTTGGCGTGACGCCGTTGC', 'GTTGGCGTGACGCCGTTGCT', 'TTGGCGTGACGCCGTTGCTG', 'TGGCGTGACGCCGTTGCTGC', 'GGCGTGACGCCGTTGCTGCG', 'GCGTGACGCCGTTGCTGCGC', 'CGTGACGCCGTTGCTGCGCT', 'GTGACGCCGTTGCTGCGCTC', 'TGACGCCGTTGCTGCGCTCT', 'GACGCCGTTGCTGCGCTCTT', 'ACGCCGTTGCTGCGCTCTTG', 'CGCCGTTGCTGCGCTCTTGG', 'GCCGTTGCTGCGCTCTTGGG', 'CCGTTGCTGCGCTCTTGGGG', 'CGTTGCTGCGCTCTTGGGGG', 'GTTGCTGCGCTCTTGGGGGT', 'TTGCTGCGCTCTTGGGGGTA', 'TGCTGCGCTCTTGGGGGTAG', 'GCTGCGCTCTTGGGGGTAGA', 'CTGCGCTCTTGGGGGTAGAC', 'TGCGCTCTTGGGGGTAGACG', 'GCGCTCTTGGGGGTAGACGC', 'CGCTCTTGGGGGTAGACGCG', 'GCTCTTGGGGGTAGACGCGT', 'CTCTTGGGGGTAGACGCGTC', 'TCTTGGGGGTAGACGCGTCT', 'CTTGGGGGTAGACGCGTCTC', 'TTGGGGGTAGACGCGTCTCT', 'TGGGGGTAGACGCGTCTCTC', 'GGGGGTAGACGCGTCTCTCA', 'GGGGTAGACGCGTCTCTCAG']),
                            (500, ["GTCTCCGAGCGATCTATCCACGACCAATTTGACATGGGTGCGCCGTTTGTAAAGGCCGTGGACAAAGCAGAACCCCCGGCACCGAGGGGGGCCGGGGGCCTGTTGGCGTGACGCCGTTGCTGCGCTCTTGGGGGTAGACGCGTCTCTCAG"]),
                            (-4, ["GTCTCCGAGCGATCTATCCACGACCAATTTGACATGGGTGCGCCGTTTGTAAAGGCCGTGGACAAAGCAGAACCCCCGGCACCGAGGGGGGCCGGGGGCCTGTTGGCGTGACGCCGTTGCTGCGCTCTTGGGGGTAGACGCGTCTCTCAG"])
                        ])
def test_create_kmers(kmer_len, expected):
    ''' Test kmer generation method '''
    actual_genome = ("GTCTCCGAGCGATCTATCCACGACCAATTTGACATGGGTGCGCCGTTTGT"
                    "AAAGGCCGTGGACAAAGCAGAACCCCCGGCACCGAGGGGGGCCGGGGGCC"
                    "TGTTGGCGTGACGCCGTTGCTGCGCTCTTGGGGGTAGACGCGTCTCTCAG")
    #expected = ['GTCTCCGAGCGATCTATCCA', 'TCTCCGAGCGATCTATCCAC', 'CTCCGAGCGATCTATCCACG', 'TCCGAGCGATCTATCCACGA', 'CCGAGCGATCTATCCACGAC', 'CGAGCGATCTATCCACGACC', 'GAGCGATCTATCCACGACCA', 'AGCGATCTATCCACGACCAA', 'GCGATCTATCCACGACCAAT', 'CGATCTATCCACGACCAATT', 'GATCTATCCACGACCAATTT', 'ATCTATCCACGACCAATTTG', 'TCTATCCACGACCAATTTGA', 'CTATCCACGACCAATTTGAC', 'TATCCACGACCAATTTGACA', 'ATCCACGACCAATTTGACAT', 'TCCACGACCAATTTGACATG', 'CCACGACCAATTTGACATGG', 'CACGACCAATTTGACATGGG', 'ACGACCAATTTGACATGGGT', 'CGACCAATTTGACATGGGTG', 'GACCAATTTGACATGGGTGC', 'ACCAATTTGACATGGGTGCG', 'CCAATTTGACATGGGTGCGC', 'CAATTTGACATGGGTGCGCC', 'AATTTGACATGGGTGCGCCG', 'ATTTGACATGGGTGCGCCGT', 'TTTGACATGGGTGCGCCGTT', 'TTGACATGGGTGCGCCGTTT', 'TGACATGGGTGCGCCGTTTG', 'GACATGGGTGCGCCGTTTGT', 'ACATGGGTGCGCCGTTTGTA', 'CATGGGTGCGCCGTTTGTAA', 'ATGGGTGCGCCGTTTGTAAA', 'TGGGTGCGCCGTTTGTAAAG', 'GGGTGCGCCGTTTGTAAAGG', 'GGTGCGCCGTTTGTAAAGGC', 'GTGCGCCGTTTGTAAAGGCC', 'TGCGCCGTTTGTAAAGGCCG', 'GCGCCGTTTGTAAAGGCCGT', 'CGCCGTTTGTAAAGGCCGTG', 'GCCGTTTGTAAAGGCCGTGG', 'CCGTTTGTAAAGGCCGTGGA', 'CGTTTGTAAAGGCCGTGGAC', 'GTTTGTAAAGGCCGTGGACA', 'TTTGTAAAGGCCGTGGACAA', 'TTGTAAAGGCCGTGGACAAA', 'TGTAAAGGCCGTGGACAAAG', 'GTAAAGGCCGTGGACAAAGC', 'TAAAGGCCGTGGACAAAGCA', 'AAAGGCCGTGGACAAAGCAG', 'AAGGCCGTGGACAAAGCAGA', 'AGGCCGTGGACAAAGCAGAA', 'GGCCGTGGACAAAGCAGAAC', 'GCCGTGGACAAAGCAGAACC', 'CCGTGGACAAAGCAGAACCC', 'CGTGGACAAAGCAGAACCCC', 'GTGGACAAAGCAGAACCCCC', 'TGGACAAAGCAGAACCCCCG', 'GGACAAAGCAGAACCCCCGG', 'GACAAAGCAGAACCCCCGGC', 'ACAAAGCAGAACCCCCGGCA', 'CAAAGCAGAACCCCCGGCAC', 'AAAGCAGAACCCCCGGCACC', 'AAGCAGAACCCCCGGCACCG', 'AGCAGAACCCCCGGCACCGA', 'GCAGAACCCCCGGCACCGAG', 'CAGAACCCCCGGCACCGAGG', 'AGAACCCCCGGCACCGAGGG', 'GAACCCCCGGCACCGAGGGG', 'AACCCCCGGCACCGAGGGGG', 'ACCCCCGGCACCGAGGGGGG', 'CCCCCGGCACCGAGGGGGGC', 'CCCCGGCACCGAGGGGGGCC', 'CCCGGCACCGAGGGGGGCCG', 'CCGGCACCGAGGGGGGCCGG', 'CGGCACCGAGGGGGGCCGGG', 'GGCACCGAGGGGGGCCGGGG', 'GCACCGAGGGGGGCCGGGGG', 'CACCGAGGGGGGCCGGGGGC', 'ACCGAGGGGGGCCGGGGGCC', 'CCGAGGGGGGCCGGGGGCCT', 'CGAGGGGGGCCGGGGGCCTG', 'GAGGGGGGCCGGGGGCCTGT', 'AGGGGGGCCGGGGGCCTGTT', 'GGGGGGCCGGGGGCCTGTTG', 'GGGGGCCGGGGGCCTGTTGG', 'GGGGCCGGGGGCCTGTTGGC', 'GGGCCGGGGGCCTGTTGGCG', 'GGCCGGGGGCCTGTTGGCGT', 'GCCGGGGGCCTGTTGGCGTG', 'CCGGGGGCCTGTTGGCGTGA', 'CGGGGGCCTGTTGGCGTGAC', 'GGGGGCCTGTTGGCGTGACG', 'GGGGCCTGTTGGCGTGACGC', 'GGGCCTGTTGGCGTGACGCC', 'GGCCTGTTGGCGTGACGCCG', 'GCCTGTTGGCGTGACGCCGT', 'CCTGTTGGCGTGACGCCGTT', 'CTGTTGGCGTGACGCCGTTG', 'TGTTGGCGTGACGCCGTTGC', 'GTTGGCGTGACGCCGTTGCT', 'TTGGCGTGACGCCGTTGCTG', 'TGGCGTGACGCCGTTGCTGC', 'GGCGTGACGCCGTTGCTGCG', 'GCGTGACGCCGTTGCTGCGC', 'CGTGACGCCGTTGCTGCGCT', 'GTGACGCCGTTGCTGCGCTC', 'TGACGCCGTTGCTGCGCTCT', 'GACGCCGTTGCTGCGCTCTT', 'ACGCCGTTGCTGCGCTCTTG', 'CGCCGTTGCTGCGCTCTTGG', 'GCCGTTGCTGCGCTCTTGGG', 'CCGTTGCTGCGCTCTTGGGG', 'CGTTGCTGCGCTCTTGGGGG', 'GTTGCTGCGCTCTTGGGGGT', 'TTGCTGCGCTCTTGGGGGTA', 'TGCTGCGCTCTTGGGGGTAG', 'GCTGCGCTCTTGGGGGTAGA', 'CTGCGCTCTTGGGGGTAGAC', 'TGCGCTCTTGGGGGTAGACG', 'GCGCTCTTGGGGGTAGACGC', 'CGCTCTTGGGGGTAGACGCG', 'GCTCTTGGGGGTAGACGCGT', 'CTCTTGGGGGTAGACGCGTC', 'TCTTGGGGGTAGACGCGTCT', 'CTTGGGGGTAGACGCGTCTC', 'TTGGGGGTAGACGCGTCTCT', 'TGGGGGTAGACGCGTCTCTC', 'GGGGGTAGACGCGTCTCTCA', 'GGGGTAGACGCGTCTCTCAG']

    actual = test_dna.create_kmers(actual_genome, kmer_len)
    assert actual == expected


def test_calc_jaccard():
    ''' Test jaccard calculation '''
    # EXPECTED JACCARD VALUE SETUP
    set1 = set(test_dna.kmers) # Blessica
    set2 = set(compare_dna.kmers) # Ryadel
    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))
    expected_jaccard_val = round(intersection / union, 4)
    #expected_jaccard_val = 0.2857

    assert test_dna.calc_jaccard(compare_dna) == expected_jaccard_val
