PHAGE_REF_DB_PATH = "/projects/laal5512/tools/Phage-EnrichSeq/database/ref_genomes/"
NCBI_TO_TAXID_PATH = "/projects/laal5512/ncbi_map.tab"

OUTPUT_DIRECTORY = "/projects/laal5512/benchmarking_output/"
