name: enrichseq-cdci-actions
on: 
  pull_request:
    branches:
      - main 
jobs:
  basic-testing:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment_mac.yml
          activate-environment: enrichseq
          auto-activate-base: false 
      - name: conda env check
        shell: bash -l {0}
        run: ls $CONDA/envs/;
             conda info --envs;
      - name: run unit tests (PathOrganizer)
        shell: bash -l {0}
        run: pytest PathOrganizer_module/
      - name: run unit tests (ReadSimulator)
        shell: bash -l {0}
        run: pytest readsimulator_module/
      - name: run unit tests (MergeOverlap)
        shell: bash -l {0}
        run: pytest mergeoverlap_filter_module/

  ubuntu-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment_linux.yml
          activate-environment: enrichseq
          auto-activate-base: false 
      - name: conda env check
        shell: bash -l {0}
        run: ls $CONDA/envs/;
             conda info --envs;
      - name: run unit tests (PathOrganizer)
        shell: bash -l {0}
        run: pytest PathOrganizer_module/
      - name: run unit tests (ReadSimulator)
        shell: bash -l {0}
        run: pytest readsimulator_module/
      - name: run unit tests (MergeOverlap)
        shell: bash -l {0}
        run: pytest mergeoverlap_filter_module/